version: '3.8'

services:
  api-gateway-proxy:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - REDIS_URI=redis://redis:6379
      - EXECUTOR_URL=http://executor:3001
      - PROXY_PORT=8080
    depends_on:
      - mongo
      - redis
    networks:
      - api-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - api-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - api-network

volumes:
  mongo_data:
  redis_data:

networks:
  api-network:
    driver: bridge 